apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  description: ${{values.description | dump}}
  links:
  - url: https://example.com/user
    title: Examples Users
    icon: user
  - url: https://example.com/group
    title: Example Group
    icon: group
  - url: https://example.com/cloud
    title: Link with Cloud Icon
    icon: cloud
  - url: https://example.com/dashboard
    title: Dashboard
    icon: dashboard
  - url: https://example.com/help
    title: Support
    icon: help
  - url: https://example.com/web
    title: Website
    icon: web
  - url: https://example.com/alert
    title: Alerts
    icon: alert
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump}}